### ISSUE TITLE
How to generate all table`s factory whit one command?

### ISSUE THREAD

**Issue by OranTing** [aiiro/laravel-factory-generator#2]
Hello,I can use this command to generate table users
`php artisan generate:factory users`
But I have lots of tables.
I want to generate all tables factories use one command.
such us 
`php artisan generate:factory`

is there a way to do this?

Thanks

**Comment by aiiro** [comment]
Hi, @OranTing 

Sorry for that I haven't noticed this issue.

Unfortunately we can't generate all tables factories.
But I think that your suggestion is good.

So, I will try to implement the feature.

Thanks.

**Comment by aiiro** [comment]
56a5610ac8b4042f0f70525d8692b7898000794a
I have added the feature to generate factories of all tables in database.
Please read README to find how to run the command.
